Sky130: Add lib to contain all logic libraries, add hd low leakage logic library
siliconcompiler/lambdapdk pull request #28
Opened 2024-03-07 11:51 UTC by ubfx

This is my attempt at starting to move in more Sky130 logic libraries (low leakage, high speed, low speed, etc).

I figured there's so much infrastructure built on top of the current `sky130hd` library that we shouldn't change it straight away, but on the other hand, we have to start somewhere moving in the other logic libs. This patch adds a new library `sky130sc`, sc for standard cells, which could become the umbrella library for all sky130 logic libraries (hd, hdll, hs, ...) at some point, just like `gf180mcu` is for gf180. But for now, it can coexist with the tried and tested `sky130hd`.

The idea would be to add a temporary/development target (`skywater130_demo_devel` or so) to siliconcompiler which would allow us to add some testing without touching the good old `skywater130_demo`. (Also, we need a target for the lambdalib generating step).

For now, the new `sky130sc` setup will load the existing `sky130hd`, but also the newly added `sky130hdll` (high density low leakage). A few notes on the `sky130hdll`:

1. All files were taken from open_pdks, as described in the Readme, but there are some small changes to lefs and libs:
   - Add a dummy cut layer between `pwell` and `li1` to make Cadence accept the LEF. (-> https://github.com/RTimothyEdwards/open_pdks/issues/435)
   - Replace illegal floats with ints in libs to make Cadence accept the lib (-> https://github.com/efabless/skywater-pdk-libs-sky130_fd_sc_hdll/pull/7)
 2. The lambdalib was "generated" by substituting `_hd__` for `_hdll__` for now. When we have the siliconcompiler target, we should be able to just generate it normally.
 3. Yosys techmapping files were produced the same way.

I know patching the LEFs and libs is not ideal, but I assume there will be some more patches necessary until we get all of the different logic libs working. And maybe I will be able to upstream some of these patches with open_pdks until then. I would suggest doing a more thorough review of all necessary patches when we get all of libraries working.

2024-03-07 15:22 UTC, gadfort commented
@ubfx to generate the lambdalib information just use: https://github.com/siliconcompiler/lambdapdk/blob/main/scripts/generate_lamdbalib.py

If you just want to do some testing, you can always create a temporary target on a branch here:
```
... sky130_dev.py
(copy in regular setup or import it and call it)
chip.use(sky130sc)
chip.set('asic', 'logiclib', '...')
```

And use it like:
```
sc -target lambdapdk.sky130.target.sky130_dev
```
or
```
from lambdapdk.sky130.target import sky130_dev

...
  chip.load_target(sky130_dev)
...
```

If you want to check against a broader set of designs you can also try out: https://github.com/siliconcompiler/scgallery

2024-03-07 16:01 UTC, ubfx commented
I tested the new lib locally on yosys+OpenROAD and Cadence on a few designs, but thought we would probably want to some in-tree testing (on CI) before moving the main target over to the new lib. Especially since all the tests on siliconcompiler just use the `hd` library currently.

Are you against having two targets in-tree for a transitionary period?

2024-03-08 14:33 UTC, gadfort commented
@ubfx I would prefer to no have a temporary target in SC. We could switch the target in SC to point to this file instead, if the default behavior is the hd lib nothing should change and that would make it possible to do some testing without adding a target.

2024-03-08 14:47 UTC, gadfort requested changes
Looks good, I don't think there is too much to address, so should be fairly easy.

2024-03-08 16:59 UTC, ubfx commented on lambdapdk/sky130/libs/sky130sc.py
> +                                   ("hdll", ["unithd", "unithddbl"], "1v44")):
Yes, the idea was to get all of the logic libs into this file slowly but surely. Having the sites in the list is the preparation for adding the hs library, which has different sites.

2024-03-08 17:02 UTC, ubfx commented on lambdapdk/sky130/README.md
> +Work in Progress
These two comments are meant to indicate that the source libs themselves (at open_pdks) are in motion, as we're merging the LEF changes (and possibly more) upstream. I just wanted to dissuade people from using the current state of the files as a golden reference.

2024-03-08 17:28 UTC, gadfort commented
Please add the new module to:
* https://github.com/siliconcompiler/lambdapdk/blob/main/tests/test_lambda.py
* https://github.com/siliconcompiler/lambdapdk/blob/main/tests/test_paths.py

2024-03-08 19:55 UTC, gadfort requested changes
It appears there are no full or half adders in the hdll library, please remove that enablement and it should be good to merge.

2024-03-08 19:55 UTC, gadfort commented on lambdapdk/sky130/libs/sky130hdll/techmap/yosys/cells_adders.v
> +            );
these cells do no exist in the hdll library, please remove this file and regenerate the lamdbalib

2024-03-08 21:15 UTC, ubfx commented on lambdapdk/sky130/libs/sky130hdll/techmap/yosys/cells_adders.v
> +            );
Ah, thanks I missed that. Apparently, there's also no positive-enable latch, but the negative-enable latch exists

2024-03-08 21:21 UTC, gadfort commented
@ubfx looks great, just need to redo the lambdalib generation since the files have references to the half and full adders.

2024-03-08 22:09 UTC, ubfx commented
> @ubfx looks great, just need to redo the lambdalib generation since the files have references to the half and full adders.

For the ICGC and the p-latch, I'm now getting something like this:
```
module la_latq(d, clk, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  \$_DLATCH_P_  q_reg /* _0_ */ (
    .D(d),
    .E(clk),
    .Q(q)
  );
endmodule
```
Should I add a techmapping of `DLATCH_P` to an inverter + the negative-gate latch?

2024-03-08 22:16 UTC, gadfort commented
@ubfx yeah, I think that would be correct.

2024-03-08 22:52 UTC, gadfort approved these changes
Thanks. looks good.

2024-03-08 22:53 UTC, merged